package GameServer_CORBA;


/**
* GameServer_CORBA/GameServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer-CORBA.idl
* Sunday, August 9, 2020 1:25:48 o'clock AM EDT
*/

public interface GameServer extends GameServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameServer
