package GameServer_CORBA;

/**
* GameServer_CORBA/GameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer-CORBA.idl
* Sunday, August 9, 2020 1:25:48 o'clock AM EDT
*/

public final class GameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public GameServer_CORBA.GameServer value = null;

  public GameServerHolder ()
  {
  }

  public GameServerHolder (GameServer_CORBA.GameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameServer_CORBA.GameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameServer_CORBA.GameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameServer_CORBA.GameServerHelper.type ();
  }

}
