package FE_CORBA;

/**
* FE_CORBA/GameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FE-CORBA.idl
* Friday, August 7, 2020 11:05:37 o'clock PM EDT
*/

public final class GameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public FE_CORBA.GameServer value = null;

  public GameServerHolder ()
  {
  }

  public GameServerHolder (FE_CORBA.GameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FE_CORBA.GameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FE_CORBA.GameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FE_CORBA.GameServerHelper.type ();
  }

}
