package FE_CORBA;


/**
* FE_CORBA/GameServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FE-CORBA.idl
* Friday, August 7, 2020 11:05:37 o'clock PM EDT
*/

public interface GameServer extends GameServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameServer
